import type { Metadata } from "next";

import "../globals.css";
import { Navbar } from "@/components/navbar/navbar";
import Footer from "@/components/footer";
import { CookieConsentProvider } from "@/context/cookies-context";
import { CookieConsentDialog } from "@/components/cookies-dialog/consnet-dialog";
import { CookieScriptLoader } from "@/components/cookies-dialog/script-loader";


export const metadata: Metadata = {
  title: "DevEdge Consulting",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        <CookieConsentProvider>
          {children}
          <CookieConsentDialog />
          <CookieScriptLoader googleAnalyticsId="G-XXXXXXXXXX" />
        </CookieConsentProvider>
        <Footer/>
      </body>
    </html>
  );
}
